/**
 * WARNING
 * This file was autogenerated by jz_preprocess from jz4760b/jz4760bxxx.h
 */
/*
 * linux/include/asm-mips/mach-jz4760b/jz4760bxxx.h
 *
 * JZ4760B XXX register definition.
 *
 * Copyright (C) 2010 Ingenic Semiconductor Co., Ltd.
 */

// 
// #ifndef __JZ4760BXXX_H__
// #define __JZ4760BXXX_H__

// 

// 
// #ifndef __MIPS_ASSEMBLER

// 
// #endif /* __MIPS_ASSEMBLER */

// 
// #endif /* __JZ4760BXXX_H__ */

// 
